### ISSUE TITLE
[plan] Iteration 1

### ISSUE THREAD

**Issue by rufuspollock** [rgrp/climate-negotiations#5]
- [ ] #2 - store raw-ish scraped text

Then three parallel directions
- Make it into a website:
  - [ ] #11 - jekyll-ize it and theme it
  - [ ] TODO - make each ENB annotatable
  - [ ] #15 - front page listing all ENBs
- Make the database - cf the data model #4 
  - [ ] #1 - DB of documents
  - [ ] #14 DB of events
- Chunk the text up
  -  [ ] #12 - chunk text

```
Raw ENB HTML => Clean Markdown / Txt => Chunks => Annotated Chunks => Database
```
